1. The resulting matrix will have dimensions (n, m). To calculate each element D[i][j] in the matrix D, k multiplications and k-1 additions are required. With n rows and m columns in the resulting matrix, these operations need to be performed n * m times, resulting in a total of n * m multiplications.

In [3]:
#2
def perform_matrix_multiplication(matrix1, matrix2):
    # For the dimensions of matrices matrix1 and matrix2
    rows1, cols1 = len(matrix1), len(matrix1[0])
    rows2, cols2 = len(matrix2), len(matrix2[0])

    # Check if the matrices can be multiplied
    if cols1 != rows2:
        raise ValueError("Incompatible matrix dimensions for multiplication")

    # Initialize the resulting matrix result_matrix with zeros
    result_matrix = [[0 for _ in range(cols2)] for _ in range(rows1)]

    # Perform matrix multiplication
    for i in range(rows1):
        for j in range(cols2):
            for k in range(cols1):
                result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]

    return result_matrix

# Example matrices
matrix_A = [[1, 4], [6, 2]]
matrix_B = [[3, 1], [9, 5]]

result_matrix = perform_matrix_multiplication(matrix_A, matrix_B)
print("Result matrix:", result_matrix)


Result matrix: [[39, 21], [36, 16]]


In [4]:
import numpy as np

def perform_matrix_multiplication_numpy(matrix1, matrix2):
    # Convert matrices to NumPy arrays
    matrix1_np, matrix2_np = np.array(matrix1), np.array(matrix2)

    # Perform matrix multiplication using NumPy
    result_np = np.dot(matrix1_np, matrix2_np)

    return result_np.tolist()  # Convert the result back to a list of lists

# Example matrices
matrix_A_np = np.array([[1, 4], [6, 2]])
matrix_B_np = np.array([[3, 1], [9, 5]])

result_matrix_numpy = perform_matrix_multiplication_numpy(matrix_A_np, matrix_B_np)
print("Result using NumPy:", result_matrix_numpy)


Result using NumPy: [[39, 21], [36, 16]]


After comparing the execution time of the above two implementations, it's evident that NumPy is generally faster than using a list of lists for matrix operations. NumPy is implemented in C and optimized for numerical computations, leveraging efficient algorithms and memory layouts. This performance advantage becomes more pronounced, especially for larger matrices. The optimized nature of NumPy operations contributes to quicker execution times compared to the equivalent operations with lists of lists in Python.

In [6]:
#7
students_record = {
    2022: {
        'Branch 1': {
            'Roll Number': 1,
            'Name': 'Tanmay',
            'Marks': {
                'Maths': 100,
                'English': 70,
                'Hindi':85
                
            }
        },
        'Branch 2': {
            'Name': 'Pratyush',
            'Marks': {
                'Maths': 100,
                'English': 70,
                'Hindi':85
        }
    },
    }
}
print("Student Name in 2022, Branch 1, Roll Number 1:", students_record[2022]['Branch 1']['Name'])
print("Maths Marks in 2022, Branch 1, Roll Number 1:", students_record[2022]['Branch 1']['Marks']['Maths'])


Student Name in 2022, Branch 1, Roll Number 1: Tanmay
Maths Marks in 2022, Branch 1, Roll Number 1: 100


In [7]:
#8
class Student:
    def __init__(self, student_id, student_name):
        self.student_id = student_id
        self.student_name = student_name
        self.subject_marks = {}

    def add_subject_marks(self, subject, marks):
        self.subject_marks[subject] = marks


class Department:
    def __init__(self, department_name):
        self.department_name = department_name
        self.students_list = []

    def add_student(self, student):
        self.students_list.append(student)


class AcademicSession:
    def __init__(self, session_year):
        self.session_year = session_year
        self.departments_list = []

    def add_department(self, department):
        self.departments_list.append(department)


# Overall database as a list of AcademicSession objects
learning_database = []

# Create AcademicSession objects
session_2022 = AcademicSession(2022)
session_2023 = AcademicSession(2023)
session_2024 = AcademicSession(2024)
session_2025 = AcademicSession(2025)

# Create Department objects
department_1 = Department('Department 1')
department_2 = Department('Department 2')

# Create Student objects
student_2022_department_1 = Student(1, 'Tanmay')
student_2022_department_1.add_subject_marks('Maths', 95)
student_2022_department_1.add_subject_marks('English', 75)
student_2022_department_1.add_subject_marks('Hindi', 90)

# Add students to departments
department_1.add_student(student_2022_department_1)

# Add departments to academic sessions
session_2022.add_department(department_1)
session_2022.add_department(department_2)

# Add academic sessions to the overall database
learning_database.append(session_2022)
learning_database.append(session_2023)
learning_database.append(session_2024)
learning_database.append(session_2025)

# Accessing data example:
print("STUDENT Name in 2022, Department 1, ID 1:", learning_database[0].departments_list[0].students_list[0].student_name)
print("Maths Marks in 2022, Department 1, ID 1:", learning_database[0].departments_list[0].students_list[0].subject_marks['Maths'])


STUDENT Name in 2022, Department 1, ID 1: Tanmay
Maths Marks in 2022, Department 1, ID 1: 95


In [10]:
#11
import numpy as np
import pandas as pd

# Generate a 20x5 matrix with random numbers drawn uniformly from the range [1, 2)
custom_matrix = np.random.uniform(1, 2, size=(20, 5))

# Create a DataFrame from the matrix with column names "x", "y", "z", "p", "q"
custom_df = pd.DataFrame(custom_matrix, columns=['x', 'y', 'z', 'p', 'q'])

# Add a new column "r" which is the sum of columns "x", "y", "z", "p", "q"
custom_df['r'] = custom_df.sum(axis=1)

# Create a column "s" with values "LT8" if "r" is less than 8, and "GT8" otherwise
custom_df['s'] = np.where(custom_df['r'] < 8, 'LT8', 'GT8')

# Find the number of rows where the value in column "s" is "LT8"
lt8_count_custom = (custom_df['s'] == 'LT8').sum()

# Find the standard deviation of column "r" for rows where "s" is "LT8" and "GT8" respectively
std_lt8_custom = custom_df.loc[custom_df['s'] == 'LT8', 'r'].std()
std_gt8_custom = custom_df.loc[custom_df['s'] == 'GT8', 'r'].std()

# Display the modified DataFrame
print("Modified DataFrame:")
print(custom_df)

# Display the results
print("\nNumber of rows where 's' is 'LT8':", lt8_count_custom)
print("Standard deviation of 'r' for rows where 's' is 'LT8':", std_lt8_custom)
print("Standard deviation of 'r' for rows where 's' is 'GT8':", std_gt8_custom)



Modified DataFrame:
           x         y         z         p         q         r    s
0   1.546441  1.856769  1.240104  1.674169  1.933629  8.251112  GT8
1   1.259143  1.712618  1.362062  1.638708  1.445280  7.417810  LT8
2   1.010227  1.190712  1.301164  1.965230  1.242804  6.710136  LT8
3   1.688097  1.711961  1.483205  1.099862  1.402892  7.386016  LT8
4   1.171004  1.261370  1.789237  1.199238  1.731526  7.152374  LT8
5   1.765291  1.364975  1.953523  1.506646  1.702128  8.292563  GT8
6   1.743734  1.123079  1.483912  1.959431  1.949985  8.260141  GT8
7   1.340564  1.329647  1.585643  1.290112  1.473397  7.019363  LT8
8   1.810692  1.326200  1.007336  1.098786  1.910026  7.153040  LT8
9   1.650443  1.155425  1.494828  1.401758  1.076796  6.779250  LT8
10  1.382568  1.505027  1.562177  1.665713  1.952136  8.067621  GT8
11  1.939491  1.814317  1.234439  1.022141  1.696943  7.707331  LT8
12  1.757011  1.940241  1.382252  1.734689  1.992897  8.807089  GT8
13  1.383933  1.866730  1.77

In [11]:
#12
import numpy as np

# Example 1: Broadcasting a scalar to an array
custom_scalar = 3
custom_array_1 = np.array([1, 2, 3, 4, 5])

custom_result_1 = custom_scalar * custom_array_1

print("Custom Array 1:", custom_array_1)
print("Custom Result 1:", custom_result_1)

# Example 2: Broadcasting a 1D array to a 2D array
custom_array_2d = np.array([[1, 2, 3], [4, 5, 6]])

custom_array_1d = np.array([10, 20, 30])

custom_result_2 = custom_array_2d + custom_array_1d

print("\nCustom Array 2D:")
print(custom_array_2d)
print("\nCustom Array 1D:", custom_array_1d)
print("Custom Result 2:")
print(custom_result_2)


Custom Array 1: [1 2 3 4 5]
Custom Result 1: [ 3  6  9 12 15]

Custom Array 2D:
[[1 2 3]
 [4 5 6]]

Custom Array 1D: [10 20 30]
Custom Result 2:
[[11 22 33]
 [14 25 36]]
